const defaultGaleries = [
  {'isEnabled':false,'title':'Fotos não identificadas','code':'ni','tabCode':'','display':'Fotos não identificadas - ni'},
  {'isEnabled':false,'title':'Pódio','code':'podio','tabCode':'','display':'Pódio - podio'},
  {'isEnabled':false,'title':'Largada','code':'largada','tabCode':'','display':'Largada - largada'},
  {'isEnabled':false,'title':'Chegada','code':'chegada','tabCode':'','display':'Chegada - chegada'},
  {'isEnabled':false,'title':'Kitesurf','code':'kitesurf','tabCode':'','display':'Kitesurf - kitesurf'},
  {'isEnabled':false,'title':'Concentração','code':'concentracao','tabCode':'','display':'Concentração - concentracao'},
  {'isEnabled':false,'title':'Feminino','code':'feminino','tabCode':'','display':'Feminino - feminino'},
  {'isEnabled':false,'title':'Masculino','code':'masculino','tabCode':'','display':'Masculino - masculino'},
  {'isEnabled':false,'title':'Triathlon','code':'triathlon','tabCode':'','display':'Triathlon - triathlon'},
  {'isEnabled':false,'title':'Infantil','code':'infantil','tabCode':'','display':'Infantil - infantil'},
  {'isEnabled':false,'title':'Downhill','code':'downhill','tabCode':'','display':'Downhill - downhill'},
  {'isEnabled':false,'title':'Corrida','code':'corrida','tabCode':'','display':'Corrida - corrida'},
  {'isEnabled':false,'title':'Premiação','code':'premiacao','tabCode':'','display':'Premiação - premiacao'},
  {'isEnabled':false,'title':'Festa','code':'festa','tabCode':'','display':'Festa - festa'},
  {'isEnabled':false,'title':'Ciclismo','code':'ciclismo','tabCode':'','display':'Ciclismo - ciclismo'},
  {'isEnabled':false,'title':'Natação','code':'natacao','tabCode':'','display':'Natação - natacao'},
  {'isEnabled':false,'title':'Sexta Feira','code':'sexta','tabCode':'','display':'Sexta Feira - sexta'},
  {'isEnabled':false,'title':'Staff','code':'staff','tabCode':'','display':'Staff - staff'},
  {'isEnabled':false,'title':'Largada Bike','code':'largada bike','tabCode':'','display':'Largada Bike - largada bike'},
  {'isEnabled':false,'title':'Master','code':'master','tabCode':'','display':'Master - master'},
  {'isEnabled':false,'title':'Curitiba','code':'curitiba','tabCode':'','display':'Curitiba - curitiba'},
  {'isEnabled':false,'title':'Kids','code':'kids','tabCode':'','display':'Kids - kids'},
  {'isEnabled':false,'title':'Largada Sábado','code':'largadasabado','tabCode':'','display':'Largada Sábado - largadasabado'},
  {'isEnabled':false,'title':'Chegada Sábado','code':'chegadasabado','tabCode':'','display':'Chegada Sábado - chegadasabado'},
  {'isEnabled':false,'title':'Pódio Sábado','code':'podiosabado','tabCode':'','display':'Pódio Sábado - podiosabado'},
  {'isEnabled':false,'title':'Largada Domingo','code':'largadadomingo','tabCode':'','display':'Largada Domingo - largadadomingo'},
  {'isEnabled':false,'title':'Chegada Domingo','code':'chegadadomingo','tabCode':'','display':'Chegada Domingo - chegadadomingo'},
  {'isEnabled':false,'title':'Pódio Domingo','code':'podiodomingo','tabCode':'','display':'Pódio Domingo - podiodomingo'},
  {'isEnabled':false,'title':'1.500 Feminino','code':'1500feminino','tabCode':'','display':'1.500 Feminino - 1500feminino'},
  {'isEnabled':false,'title':'1.500 Masculino','code':'1500masculino','tabCode':'','display':'1.500 Masculino - 1500masculino'},
  {'isEnabled':false,'title':'Fotos não identificadas Natação','code':'nina','tabCode':'','display':'Fotos não identificadas Natação - nina'},
  {'isEnabled':false,'title':'Fotos não identificadas Ciclismo','code':'nici','tabCode':'','display':'Fotos não identificadas Ciclismo - nici'},
  {'isEnabled':false,'title':'Fotos não identificadas Corrida','code':'nico','tabCode':'','display':'Fotos não identificadas Corrida - nico'},
  {'isEnabled':false,'title':'Chegada Iniciantes','code':'chegadainiciantes','tabCode':'','display':'Chegada Iniciantes - chegadainiciantes'},
  {'isEnabled':false,'title':'Travessia','code':'travessia','tabCode':'','display':'Travessia - travessia'},
  {'isEnabled':false,'title':'3.000 metros','code':'3000metros','tabCode':'','display':'3.000 metros - 3000metros'},
  {'isEnabled':false,'title':'Pódio 3.000','code':'podio3000','tabCode':'','display':'Pódio 3.000 - podio3000'},
  {'isEnabled':false,'title':'750 metros','code':'750metros','tabCode':'','display':'750 metros - 750metros'},
  {'isEnabled':false,'title':'200 metros','code':'200metros','tabCode':'','display':'200 metros - 200metros'},
  {'isEnabled':false,'title':'Congresso','code':'congresso','tabCode':'','display':'Congresso - congresso'},
  {'isEnabled':false,'title':'1.500 metros','code':'1500metros','tabCode':'','display':'1.500 metros - 1500metros'},
  {'isEnabled':false,'title':'600 metros','code':'600metros','tabCode':'','display':'600 metros - 600metros'},
  {'isEnabled':false,'title':'Remada','code':'remada','tabCode':'','display':'Remada - remada'},
  {'isEnabled':false,'title':'2.000 metros','code':'2000metros','tabCode':'','display':'2.000 metros - 2000metros'},
  {'isEnabled':false,'title':'Surf','code':'surf','tabCode':'','display':'Surf - surf'},
  {'isEnabled':false,'title':'Fotógrafo 1','code':'fotografo1','tabCode':'','display':'Fotógrafo 1 - fotografo1'},
  {'isEnabled':false,'title':'Infanto Juvenil','code':'infantojuvenil','tabCode':'','display':'Infanto Juvenil - infantojuvenil'},
  {'isEnabled':false,'title':'Juvenil','code':'juvenil','tabCode':'','display':'Juvenil - juvenil'},
  {'isEnabled':false,'title':'Master A','code':'mastera','tabCode':'','display':'Master A - mastera'},
  {'isEnabled':false,'title':'Master B','code':'masterb','tabCode':'','display':'Master B - masterb'},
  {'isEnabled':false,'title':'Master C','code':'masterc','tabCode':'','display':'Master C - masterc'},
]

export default defaultGaleries
